# Generated by Django 5.0.6 on 2024-06-11 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonInformation',
            fields=[
                ('anonim_uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('des_weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('activity', models.CharField()),
                ('calorie', models.FloatField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField()),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('des_weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('activity', models.CharField()),
                ('calorie', models.FloatField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
