# Generated by Django 5.0.6 on 2024-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='calorie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
